"""empty message

Revision ID: acb44d072c94
Revises:
Create Date: 2025-06-05 08:56:57.220858

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "acb44d072c94"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_diaryentry", schema=None) as batch_op:
        batch_op.alter_column(
            "category_id",
            existing_type=sa.CHAR(length=32),
            type_=sa.String(),
            nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.CHAR(length=32),
            type_=sa.CHAR(length=256),
            existing_nullable=False,
        )

    with op.batch_alter_table("app_todo", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.CHAR(length=32),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "category_id",
            existing_type=sa.CHAR(length=32),
            type_=sa.String(),
            existing_nullable=False,
        )

    with op.batch_alter_table("app_todocategory", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.CHAR(length=32),
            type_=sa.String(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_todocategory", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.String(),
            type_=sa.CHAR(length=32),
            existing_nullable=False,
        )

    with op.batch_alter_table("app_todo", schema=None) as batch_op:
        batch_op.alter_column(
            "category_id",
            existing_type=sa.String(),
            type_=sa.CHAR(length=32),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.String(),
            type_=sa.CHAR(length=32),
            existing_nullable=False,
        )

    with op.batch_alter_table("app_diaryentry", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.CHAR(length=256),
            type_=sa.CHAR(length=32),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "category_id",
            existing_type=sa.String(),
            type_=sa.CHAR(length=32),
            nullable=True,
        )

    # ### end Alembic commands ###
