"""Initial tables

Revision ID: b655de7ecc6b
Revises: 
Create Date: 2026-01-07 13:06:59.929891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b655de7ecc6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_todocategory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('deactivate_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_diaryentry',
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('id', sa.CHAR(length=256), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['app_todocategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_diaryentry', schema=None) as batch_op:
        batch_op.create_index('app_diaryentry_category_id_f4e1efad', ['category_id'], unique=False)

    op.create_table('app_todo',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('complete_time', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['app_todocategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_todo', schema=None) as batch_op:
        batch_op.create_index('app_todo_category_id_660031a8', ['category_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_todo', schema=None) as batch_op:
        batch_op.drop_index('app_todo_category_id_660031a8')

    op.drop_table('app_todo')
    with op.batch_alter_table('app_diaryentry', schema=None) as batch_op:
        batch_op.drop_index('app_diaryentry_category_id_f4e1efad')

    op.drop_table('app_diaryentry')
    op.drop_table('app_todocategory')
    # ### end Alembic commands ###
