version: '3.7'

services:
  web:
    build:
      context: ./backend
      target: build
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput && uwsgi config/uwsgi.ini"
    ports:
      - 9191:8000
    volumes:
      - "sqlite_data:/app/data"
      - "assets:/static"
    environment:
      - ALLOWED_HOSTS=localhost,0.0.0.0
      - DEBUG=0
      - SECRET_KEY=${SECRET_KEY}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - STATIC_ROOT=/static

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - "assets:/static"

volumes:
  sqlite_data:
  assets:
