version: '3.7'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: uwsgi config/uwsgi.ini
    ports:
      - 8000:8080
    environment:
      - ALLOWED_HOSTS=localhost,0.0.0.0
      - DEBUG=0
      - SECRET_KEY=test
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
  db:
    image: postgres:14.1-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}

volumes:
  postgres_data:
