# Generated by Django 4.0.4 on 2023-01-13 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_diaryentry"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Todos",
            new_name="Todo",
        ),
    ]
