# Generated by Django 4.1.7 on 2023-10-27 17:20

from django.db import migrations, models
import django.db.models.deletion


def create_misc_category(apps, schema_editor):
    Category = apps.get_model("app", "TodoCategory")
    Todo = apps.get_model("app", "Todo")
    Todo.objects.filter(category__isnull=True).update(
        category=Category.objects.create(name="Miscellaneous")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_todo_text"),
    ]

    operations = [
        migrations.RunPython(
            create_misc_category, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="todo",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todos",
                to="app.todocategory",
            ),
        ),
    ]
