# Generated by Django 4.0.4 on 2022-06-03 19:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todos",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Todo UUID",
                    ),
                ),
                ("text", models.CharField(max_length=256, verbose_name="What to do?")),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time todo created"
                    ),
                ),
                (
                    "complete_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Time todo completed"
                    ),
                ),
            ],
            options={
                "ordering": ["-create_time"],
            },
        ),
    ]
