# Generated by Django 4.0.4 on 2022-08-25 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_todocategory_options_todocategory_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='app.todocategory'),
        ),
    ]
